// ============================================================================
//  VISTA CLIENT (real-extraction edition)
//  Dev with no VITE_VISTA_BASE: serves REAL VOX data from the extraction
//  (src/mockVistaData.js, generated by convert_extraction.py).
//  Prod with VITE_VISTA_BASE set: calls the real Vista/Apigee endpoints.
//  Same function signatures either way — App.jsx never changes.
// ============================================================================
import { FILMS, SESSIONS, seatPlan, BOOKING, CINEMAS, DATA_DATES } from "./mockVistaData.js";

const BASE = import.meta.env.VITE_VISTA_BASE || "";
const USE_MOCK = !BASE;
const V2 = `${BASE}/vistatickets/vista/v2`;

const HEADERS = {
  // Authorization: `Bearer ${TOKEN}`,   // production: served by a token proxy
  // "x-api-key": import.meta.env.VITE_VISTA_API_KEY,
};
const delay = (ms) => new Promise((r) => setTimeout(r, ms));

async function getJson(url) {
  const r = await fetch(url, { headers: HEADERS });
  if (!r.ok) throw new Error(`Vista ${r.status} for ${url}`);
  return r.json();
}

// "Today" for the demo: use the real current date if the extraction covers it,
// otherwise fall back to the first extracted date (so the demo never goes empty
// after the coverage window passes).
export function demoDate() {
  const today = new Date().toISOString().slice(0, 10);
  return DATA_DATES.includes(today) ? today : DATA_DATES[0];
}

export function getCinemas() {
  return CINEMAS.map((c) => ({ id: c.ID, name: c.Name }));
}

// --- Reference data ---------------------------------------------------------

export async function getScheduledFilms(cinemaId) {
  let value;
  if (USE_MOCK) {
    await delay(200);
    const d = demoDate();
    // Only films that actually have sessions today at this cinema
    const todayFilmIds = new Set(SESSIONS.filter((s) => s.CinemaId === cinemaId && s.Showtime.startsWith(d)).map((s) => s.ScheduledFilmId));
    value = FILMS.filter((f) => f.CinemaId === cinemaId && todayFilmIds.has(f.ScheduledFilmId));
  } else {
    ({ value } = await getJson(`${V2}/OData/ScheduledFilms?$format=json&$filter=CinemaId eq '${cinemaId}'`));
  }
  return value.map((f) => ({
    id: f.ScheduledFilmId,
    title: f.Title,
    rating: f.Rating,
    runtime: Number(f.RunTime) || 0,
    genre: f.genre || "",
    language: f.Language || "",
    synopsis: f.Synopsis || "",
    posterUrl: f.posterUrl || null,
    tint: f.tint || ["#63418D", "#B6186C"],
  }));
}

export async function getSessions(cinemaId, scheduledFilmId) {
  let value;
  if (USE_MOCK) {
    await delay(200);
    const d = demoDate();
    value = SESSIONS.filter((s) => s.CinemaId === cinemaId && s.Showtime.startsWith(d));
  } else {
    ({ value } = await getJson(`${V2}/OData/Sessions?$format=json&$filter=CinemaId eq '${cinemaId}'`));
  }
  return value
    .filter((s) => !scheduledFilmId || s.ScheduledFilmId === scheduledFilmId)
    .map((s) => ({
      sessionId: s.SessionId,
      time: (s.Showtime || "").slice(11, 16),
      screen: s.ScreenName,
      exp: (s.SessionAttributesNames && s.SessionAttributesNames[0]) || "2D",
      seatsAvailable: s.SeatsAvailable,
    }))
    .sort((a, b) => a.time.localeCompare(b.time));
}

export async function getSeatPlan(cinemaId, sessionId) {
  let data;
  if (USE_MOCK) { await delay(250); data = seatPlan(Number(sessionId) % 97); }
  else data = await getJson(`${V2}/Data/Cinemas/${cinemaId}/sessions/${sessionId}/seat-plan`);
  const area = data.SeatLayoutData.Areas[0];
  return area.Rows.map((row) => ({
    row: row.PhysicalName,
    seats: row.Seats.map((s) => ({
      id: `${row.PhysicalName}${Number(s.Id)}`,
      rowIndex: s.Position.RowIndex,
      colIndex: s.Position.ColumnIndex,
      status: s.Status,
      premium: s.areaCategoryCode === "0000000001",
    })),
  }));
}

// --- Booking / cancellation -------------------------------------------------

export async function searchBooking(ref) {
  // Demo bookings made during this session take priority.
  try {
    const store = JSON.parse(localStorage.getItem("vox_bookings") || "[]");
    const hit = store.find((b) => b.ref && ref && b.ref.toUpperCase() === String(ref).toUpperCase());
    if (hit) {
      return {
        ref: hit.ref, movieTitle: hit.movieTitle, showtime: hit.showtime,
        screen: hit.screen, seats: hit.seats,
        refundAmount: hit.total, currency: "AED", cancelled: !!hit.cancelled,
      };
    }
  } catch {}
  let b;
  if (USE_MOCK) { await delay(250); b = BOOKING; }
  else {
    const r = await fetch(`${BASE}/vistatickets/loyaltyalternate/v1/bookingsearch`, {
      method: "POST",
      headers: { ...HEADERS, "Content-Type": "application/json" },
      body: JSON.stringify({ BookingId: ref }),
    });
    b = (await r.json()).Booking;
  }
  return {
    ref: b.BookingId,
    movieTitle: b.FilmTitle,
    showtime: (b.Showtime || "").slice(11, 16),
    screen: b.ScreenName,
    seats: b.Seats,
    refundAmount: b.TotalValueCents / 100,
    currency: "AED",
  };
}

export async function refundBooking(ref) {
  if (USE_MOCK) { await delay(250); return { Result: 0, ErrorDescription: "OK", RefundReference: "RF" + Date.now() }; }
  const r = await fetch(`${V2}/RESTBooking.svc/booking/refund`, {
    method: "POST",
    headers: { ...HEADERS, "Content-Type": "application/json" },
    body: JSON.stringify({ BookingId: ref }),
  });
  return r.json();
}
