// ============================================================================
//  VISTA CLIENT (real-extraction edition)
//  Dev with no VITE_VISTA_BASE: serves REAL VOX data from the extraction
//  (src/mockVistaData.js, generated by convert_extraction.py).
//  Prod with VITE_VISTA_BASE set: calls the real Vista/Apigee endpoints.
//  Same function signatures either way — App.jsx never changes.
// ============================================================================
import { FILMS, SESSIONS, seatPlan, BOOKING, CINEMAS, DATA_DATES } from "./mockVistaData.js";
import { findBooking } from "./bookingStore.js";
import { remapDemoDate, uaeCalendarDate } from "./lib/demoDates.js";

const BASE = import.meta.env.VITE_VISTA_BASE || "";
const USE_MOCK = !BASE;
const V2 = `${BASE}/vistatickets/vista/v2`;

const HEADERS = {
  // Authorization: `Bearer ${TOKEN}`,   // production: served by a token proxy
  // "x-api-key": import.meta.env.VITE_VISTA_API_KEY,
};
const delay = (ms) => new Promise((r) => setTimeout(r, ms));

async function getJson(url) {
  const r = await fetch(url, { headers: HEADERS });
  if (!r.ok) throw new Error(`Vista ${r.status} for ${url}`);
  return r.json();
}

// Keep the displayed date honest: use the UAE calendar day when it is covered,
// otherwise show the first published programming day in the extracted window.
// A crawl made today normally starts tomorrow, so the UI says tomorrow as well.
export function demoDate() {
  const today = uaeCalendarDate();
  return DATA_DATES.includes(today) ? today : DATA_DATES[0] || today;
}

// Map explicit demo offsets within the verified dynamic programming window.
export function sourceDateForDemoDate(displayDate = demoDate()) {
  return remapDemoDate(displayDate, demoDate(), DATA_DATES);
}

export function getCinemas() {
  return CINEMAS.map((c) => ({ id: c.ID, name: c.Name, currency: c.CurrencyCode || "AED" }));
}

// --- Reference data ---------------------------------------------------------

export async function getScheduledFilms(cinemaId) {
  let value;
  if (USE_MOCK) {
    await delay(200);
    const d = sourceDateForDemoDate();
    // Only films that actually have sessions today at this cinema
    const todayFilmIds = new Set(SESSIONS.filter((s) => s.CinemaId === cinemaId && (s.SourceProgrammingDate || s.Showtime.slice(0, 10)) === d).map((s) => s.ScheduledFilmId));
    value = FILMS.filter((f) => f.CinemaId === cinemaId && todayFilmIds.has(f.ScheduledFilmId));
  } else {
    ({ value } = await getJson(`${V2}/OData/ScheduledFilms?$format=json&$filter=CinemaId eq '${cinemaId}'`));
  }
  return value.map((f) => ({
    id: f.ScheduledFilmId,
    title: f.Title,
    rating: f.Rating,
    runtime: Number(f.RunTime) || 0,
    genre: f.genre || "",
    language: f.Language || "",
    languageName: f.LanguageName || "",
    synopsis: f.Synopsis || "",
    genres: Array.isArray(f.Genres) && f.Genres.length ? f.Genres : [f.genre || "Film"],
    subtitles: Array.isArray(f.Subtitles) ? f.Subtitles : [],
    posterUrl: f.posterUrl || null,
    tint: f.tint || ["#63418D", "#B6186C"],
  }));
}

export async function getSessions(cinemaId, scheduledFilmId) {
  let value;
  if (USE_MOCK) {
    await delay(200);
    const d = sourceDateForDemoDate();
    value = SESSIONS.filter((s) => s.CinemaId === cinemaId && (s.SourceProgrammingDate || s.Showtime.slice(0, 10)) === d);
  } else {
    ({ value } = await getJson(`${V2}/OData/Sessions?$format=json&$filter=CinemaId eq '${cinemaId}'`));
  }
  return value
    .filter((s) => !scheduledFilmId || s.ScheduledFilmId === scheduledFilmId)
    .map((s) => ({
      sessionId: s.SessionId,
      time: (s.Showtime || "").slice(11, 16),
      screen: s.ScreenName,
      exp: (s.SessionAttributesNames && s.SessionAttributesNames[0]) || "2D",
      seatsAvailable: s.SeatsAvailable,
      date: demoDate(),
      sourceDate: (s.Showtime || "").slice(0, 10),
      timeSlot: s.TimeSlot || "",
      status: s.Status || "",
    }))
    .sort((a, b) => a.time.localeCompare(b.time));
}

export async function getSeatPlan(cinemaId, sessionId) {
  let data;
  if (USE_MOCK) { await delay(250); data = seatPlan(Number(sessionId) % 97); }
  else data = await getJson(`${V2}/Data/Cinemas/${cinemaId}/sessions/${sessionId}/seat-plan`);
  const area = data.SeatLayoutData.Areas[0];
  return area.Rows.map((row) => ({
    row: row.PhysicalName,
    seats: row.Seats.map((s) => ({
      id: `${row.PhysicalName}${Number(s.Id)}`,
      rowIndex: s.Position.RowIndex,
      colIndex: s.Position.ColumnIndex,
      status: s.Status,
      premium: s.areaCategoryCode === "0000000001",
    })),
  }));
}

// --- Booking / cancellation -------------------------------------------------

export async function searchBooking(ref) {
  const requestedRef = String(ref || "").trim();
  if (!requestedRef) throw new Error("A booking reference is required.");
  // Demo bookings made during this session take priority.
  const hit = findBooking(requestedRef);
  if (hit) {
    return {
      ...hit,
      refundAmount: hit.refundAmount ?? hit.total,
      currency: hit.currency || "AED",
      cancelled: Boolean(hit.cancelled),
    };
  }
  let b;
  if (USE_MOCK) {
    await delay(250);
    if (requestedRef.toUpperCase() !== String(BOOKING.BookingId).toUpperCase()) {
      throw new Error(`Booking ${requestedRef} was not found.`);
    }
    b = BOOKING;
  }
  else {
    const r = await fetch(`${BASE}/vistatickets/loyaltyalternate/v1/bookingsearch`, {
      method: "POST",
      headers: { ...HEADERS, "Content-Type": "application/json" },
      body: JSON.stringify({ BookingId: requestedRef }),
    });
    if (!r.ok) throw new Error(`Booking search failed with status ${r.status}.`);
    b = (await r.json()).Booking;
    if (!b) throw new Error(`Booking ${requestedRef} was not found.`);
  }
  return {
    ref: b.BookingId,
    movieTitle: b.FilmTitle,
    showtime: (b.Showtime || "").slice(11, 16),
    screen: b.ScreenName,
    seats: b.Seats,
    refundAmount: b.TotalValueCents / 100,
    currency: "AED",
    cancelled: false,
  };
}

export async function refundBooking(ref) {
  if (USE_MOCK) { await delay(250); return { Result: 0, ErrorDescription: "OK", RefundReference: "RF" + Date.now() }; }
  const r = await fetch(`${V2}/RESTBooking.svc/booking/refund`, {
    method: "POST",
    headers: { ...HEADERS, "Content-Type": "application/json" },
    body: JSON.stringify({ BookingId: ref }),
  });
  return r.json();
}
